repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: freeze-requirements
        name: freeze requirements.txt
        entry: make freeze
        language: system
        pass_filenames: false
        stages: [pre-commit]
